fts_wrench_transformer:
  ros__parameters:
    broadcaster_namespace: "fts_broadcaster"
    use_filtered_input: false
    target_frames:
    - "base_link"
    - "link1"
    output_topic_prefix: "~/wrench_transformed"
    tf_timeout: 0.1
