controller_manager:
  ros__parameters:
    update_rate: 2 # Hz

    joint_state_broadcaster:
        ros__parameters:
          type: joint_state_broadcaster/JointStateBroadcaster
          publish_rate: 50

    joint_group_position_controller:
        ros__parameters:
          type: effort_controllers/JointTrajectoryController

joint_group_position_controller:
  ros__parameters:
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
        - panda_finger_joint1
        - panda_finger_joint2

    gains:
      panda_joint1:         {p: 50, i: 0, d: 20}
      panda_joint2:         {p: 10000, i: 0, d: 500}
      panda_joint3:         {p: 100, i: 0, d: 10}
      panda_joint4:         {p: 1000, i: 0, d: 50}
      panda_joint5:         {p: 100, i: 0, d: 10}
      panda_joint6:         {p: 100, i: 0, d: 10}
      panda_joint7:         {p: 10, i: 0.5, d: 0.1}
      panda_finger_joint1:  {p: 100, i: 0, d: 50}
      panda_finger_joint2:  {p: 100, i: 0, d: 50}