controller_manager:
  ros__parameters:
    update_rate: 2  # Hz

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

    forward_command_controller_velocity:
      type: forward_command_controller/ForwardCommandController

    forward_command_controller_acceleration:
      type: forward_command_controller/ForwardCommandController

    forward_command_controller_illegal1:
      type: forward_command_controller/ForwardCommandController

    forward_command_controller_illegal2:
      type: forward_command_controller/ForwardCommandController

    joint_state_controller:
      type: joint_state_controller/JointStateController

forward_command_controller_position:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: position

forward_command_controller_velocity:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: velocity

forward_command_controller_acceleration:
  ros__parameters:
    joints:
      - joint1
      - joint2
    interface_name: acceleration

forward_command_controller_illegal1:
  ros__parameters:
    joints:
      - joint1
    interface_name: position

forward_command_controller_illegal2:
  ros__parameters:
    joints:
      - joint2
    interface_name: position