name: Coverage Build
on:
  pull_request:
    branches:
      - humble

jobs:
  coverage:
    name: coverage build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      ROS_DISTRO: humble
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - uses: actions/checkout@v3
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}
          import-token: ${{ secrets.GITHUB_TOKEN }}
          # build all packages listed in the meta package
          package-name:
            ros2_control_demo_example_1
            ros2_control_demo_example_2
            ros2_control_demo_example_3
            ros2_control_demo_example_4
            ros2_control_demo_example_5
            ros2_control_demo_example_6
            ros2_control_demo_example_7
            ros2_control_demo_example_8
            ros2_control_demo_example_9
            ros2_control_demo_example_12

          vcs-repo-file-url: |
            https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/ros2_control_demos-not-released.${{ env.ROS_DISTRO }}.repos?token=${{ secrets.GITHUB_TOKEN }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
          skip-tests: true
      - uses: codecov/codecov-action@v3.1.3
        with:
          file: ros_ws/lcov/total_coverage.info
          flags: unittests
          name: codecov-umbrella
      - uses: actions/upload-artifact@v3
        with:
          name: colcon-logs-coverage-ubuntu-22.04
          path: ros_ws/log
